
CREATE DATABASE IF NOT EXISTS user_info;

USE user_info;

CREATE TABLE Users (
    UserID INTEGER PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    CashappHandle VARCHAR(50) UNIQUE NOT NULL,
    Email VARCHAR(100) UNIQUE,
    PhoneNumber VARCHAR(15) UNIQUE, 
    City VARCHAR(50) NOT NULL,
    ZipCode INTEGER(5) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

